/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Booking {
  'id' : bigint,
  'status' : string,
  'eventId' : bigint,
  'userName' : string,
  'bookedAt' : bigint,
  'userId' : Principal,
  'eventTitle' : string,
  'eventDate' : bigint,
}
export interface DashboardStats {
  'publishedEvents' : bigint,
  'draftEvents' : bigint,
  'cancelledBookings' : bigint,
  'totalEvents' : bigint,
  'totalBookings' : bigint,
  'confirmedBookings' : bigint,
}
export interface Event {
  'id' : bigint,
  'status' : string,
  'title' : string,
  'createdAt' : bigint,
  'bookedCount' : bigint,
  'description' : string,
  'capacity' : bigint,
  'location' : string,
  'eventDate' : bigint,
}
export interface UserProfile { 'userName' : string, 'userId' : Principal }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bookEvent' : ActorMethod<[bigint], bigint>,
  'cancelBooking' : ActorMethod<[bigint], undefined>,
  'createEvent' : ActorMethod<
    [string, string, bigint, string, bigint, string],
    bigint
  >,
  'deleteEvent' : ActorMethod<[bigint], undefined>,
  'getAllBookings' : ActorMethod<[], Array<Booking>>,
  'getAllEvents' : ActorMethod<[], Array<Event>>,
  'getAllUsers' : ActorMethod<[], Array<UserProfile>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getEvent' : ActorMethod<[bigint], Event>,
  'getEvents' : ActorMethod<[], Array<Event>>,
  'getMyBookings' : ActorMethod<[], Array<Booking>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[string], undefined>,
  'updateEvent' : ActorMethod<
    [bigint, string, string, bigint, string, bigint, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];