/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Booking = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'eventId' : IDL.Nat,
  'userName' : IDL.Text,
  'bookedAt' : IDL.Int,
  'userId' : IDL.Principal,
  'eventTitle' : IDL.Text,
  'eventDate' : IDL.Int,
});
export const Event = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'title' : IDL.Text,
  'createdAt' : IDL.Int,
  'bookedCount' : IDL.Nat,
  'description' : IDL.Text,
  'capacity' : IDL.Nat,
  'location' : IDL.Text,
  'eventDate' : IDL.Int,
});
export const UserProfile = IDL.Record({
  'userName' : IDL.Text,
  'userId' : IDL.Principal,
});
export const DashboardStats = IDL.Record({
  'publishedEvents' : IDL.Nat,
  'draftEvents' : IDL.Nat,
  'cancelledBookings' : IDL.Nat,
  'totalEvents' : IDL.Nat,
  'totalBookings' : IDL.Nat,
  'confirmedBookings' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bookEvent' : IDL.Func([IDL.Nat], [IDL.Nat], []),
  'cancelBooking' : IDL.Func([IDL.Nat], [], []),
  'createEvent' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Int, IDL.Text, IDL.Nat, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'deleteEvent' : IDL.Func([IDL.Nat], [], []),
  'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getAllEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
  'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getEvent' : IDL.Func([IDL.Nat], [Event], ['query']),
  'getEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
  'getMyBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([IDL.Text], [], []),
  'updateEvent' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Int, IDL.Text, IDL.Nat, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Booking = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'eventId' : IDL.Nat,
    'userName' : IDL.Text,
    'bookedAt' : IDL.Int,
    'userId' : IDL.Principal,
    'eventTitle' : IDL.Text,
    'eventDate' : IDL.Int,
  });
  const Event = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'title' : IDL.Text,
    'createdAt' : IDL.Int,
    'bookedCount' : IDL.Nat,
    'description' : IDL.Text,
    'capacity' : IDL.Nat,
    'location' : IDL.Text,
    'eventDate' : IDL.Int,
  });
  const UserProfile = IDL.Record({
    'userName' : IDL.Text,
    'userId' : IDL.Principal,
  });
  const DashboardStats = IDL.Record({
    'publishedEvents' : IDL.Nat,
    'draftEvents' : IDL.Nat,
    'cancelledBookings' : IDL.Nat,
    'totalEvents' : IDL.Nat,
    'totalBookings' : IDL.Nat,
    'confirmedBookings' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bookEvent' : IDL.Func([IDL.Nat], [IDL.Nat], []),
    'cancelBooking' : IDL.Func([IDL.Nat], [], []),
    'createEvent' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Int, IDL.Text, IDL.Nat, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'deleteEvent' : IDL.Func([IDL.Nat], [], []),
    'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getAllEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
    'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getEvent' : IDL.Func([IDL.Nat], [Event], ['query']),
    'getEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
    'getMyBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([IDL.Text], [], []),
    'updateEvent' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Int, IDL.Text, IDL.Nat, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };